package forms

var inputClass = ""

var RegForm = Form{
	Fields: []Field{
		CharField{
			Name:     "first_name",
			Label:    "First Name",
			Required: true,
			HelpText: "Enter your given name.",
			Errors:   []string{},
			Attrs: map[string]any{
				"id":           "first_name",
				"name":         "first_name",
				"type":         "text",
				"class":        inputClass,
				"placeholder":  "John",
				"autocomplete": "given-name",
				"maxlength":    100,
			},
		},
		CharField{
			Name:     "last_name",
			Label:    "Last Name",
			Required: true,
			HelpText: "Enter your family name.",
			Errors:   []string{},
			Attrs: map[string]any{
				"id":           "last_name",
				"name":         "last_name",
				"type":         "text",
				"class":        inputClass,
				"placeholder":  "Doe",
				"autocomplete": "family-name",
				"maxlength":    100,
			},
		},
		CharField{
			Name:     "username",
			Label:    "Username",
			Required: true,
			HelpText: "Choose a unique username.",
			Errors:   []string{},
			Attrs: map[string]any{
				"id":           "username",
				"name":         "username",
				"type":         "text",
				"class":        inputClass,
				"placeholder":  "johndoe",
				"autocomplete": "username",
				"maxlength":    150,
			},
		},
		CharField{
			Name:     "email",
			Label:    "Email Address",
			Required: true,
			HelpText: "We'll never share your email.",
			Errors:   []string{},
			Attrs: map[string]any{
				"id":           "email",
				"name":         "email",
				"type":         "email",
				"class":        inputClass,
				"placeholder":  "john@example.com",
				"autocomplete": "email",
			},
		},
		CharField{
			Name:     "phone",
			Label:    "Phone Number",
			HelpText: "Optional.",
			Errors:   []string{},
			Attrs: map[string]any{
				"id":           "phone",
				"name":         "phone",
				"type":         "tel",
				"class":        inputClass,
				"placeholder":  "+254712345678",
				"autocomplete": "tel",
			},
		},
		CharField{
			Name:     "password",
			Label:    "Password",
			Required: true,
			HelpText: "Must be at least 8 characters.",
			Errors:   []string{},
			Attrs: map[string]any{
				"id":           "password",
				"name":         "password",
				"type":         "password",
				"class":        inputClass,
				"placeholder":  "Password",
				"autocomplete": "new-password",
				"minlength":    8,
			},
		},
		CharField{
			Name:     "confirm_password",
			Label:    "Confirm Password",
			Required: true,
			HelpText: "Re-enter your password.",
			Errors:   []string{},
			Attrs: map[string]any{
				"id":           "confirm_password",
				"name":         "confirm_password",
				"type":         "password",
				"class":        inputClass,
				"placeholder":  "Confirm Password",
				"autocomplete": "new-password",
				"minlength":    8,
			},
		},
	},
}
